name: Update gist with WakaTime stats
on:
  push:
    branches: master
  schedule:
    - cron: "45 9 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: fipped/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 20c85123b212bf4aff9b1d3ce176dd0a
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
